version: "3.1"

services:
  
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db

volumes:
  mongo-data: